#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jhighlight
Version  : 1.0.1
Release  : 1
URL      : https://github.com/codelibs/jhighlight/archive/jhighlight-1.0.1.tar.gz
Source0  : https://github.com/codelibs/jhighlight/archive/jhighlight-1.0.1.tar.gz
Source1  : https://repo1.maven.org/maven2/com/uwyn/jhighlight/1.0/jhighlight-1.0.jar
Source2  : https://repo1.maven.org/maven2/com/uwyn/jhighlight/1.0/jhighlight-1.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : CDDL-1.0 LGPL-2.1
Requires: mvn-jhighlight-data = %{version}-%{release}
Requires: mvn-jhighlight-license = %{version}-%{release}

%description
JHighlight
==================
## Overview
JHighlight is an embeddable pure Java syntax highlighting library that supports Java, HTML, XHTML, XML and LZX languages and outputs to XHTML.
It also supports RIFE templates tags and highlights them clearly so that you can easily identify the difference between your RIFE markup and the actual marked up source.

%package data
Summary: data components for the mvn-jhighlight package.
Group: Data

%description data
data components for the mvn-jhighlight package.


%package license
Summary: license components for the mvn-jhighlight package.
Group: Default

%description license
license components for the mvn-jhighlight package.


%prep
%setup -q -n jhighlight-jhighlight-1.0.1

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-jhighlight
cp COPYING %{buildroot}/usr/share/package-licenses/mvn-jhighlight/COPYING
cp LICENSE_CDDL.txt %{buildroot}/usr/share/package-licenses/mvn-jhighlight/LICENSE_CDDL.txt
cp LICENSE_LGPL.txt %{buildroot}/usr/share/package-licenses/mvn-jhighlight/LICENSE_LGPL.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/uwyn/jhighlight/1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/uwyn/jhighlight/1.0/jhighlight-1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/uwyn/jhighlight/1.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/uwyn/jhighlight/1.0/jhighlight-1.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/uwyn/jhighlight/1.0/jhighlight-1.0.jar
/usr/share/java/.m2/repository/com/uwyn/jhighlight/1.0/jhighlight-1.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-jhighlight/COPYING
/usr/share/package-licenses/mvn-jhighlight/LICENSE_CDDL.txt
/usr/share/package-licenses/mvn-jhighlight/LICENSE_LGPL.txt
